add color and multiple test arguments

diff --git a/test b/test
--- a/test
+++ b/test
@@ -2,18 +2,56 @@
 set -x
 set -e
 
-free -m
+black () { color_text 30; }
+blue () { color_text 34; }
+green () { color_text 32; }
+cyan () { color_text 36; }
+red () { color_text 31; }
+purple () { color_text 35; }
+brown () { color_text 33; }
+light_gray () { color_text 37; }
+
+color_text () {
+  while read data; do echo -e "\033[$1m$data"; done
+  echo -e -n "\033[0m" # clear the color
+}
 
 DIR=/vagrant
 
-PACKAGE=$1
-
-bash $DIR/packages/$PACKAGE/install
-
-if [ -f $DIR/packages/$PACKAGE/test.R ]; then
-    sudo R -f $DIR/packages/$PACKAGE/test.R
+if [ $# -eq 0 ]; then
+    PACKAGES=$(ls -1 -d $DIR/packages/* | tr '\n' '\0' | xargs -0 -n 1 basename)
 else
-    sudo R -e "install.packages('$PACKAGE', repos='http://cran.rstudio.com/'); library('$PACKAGE')"
+    PACKAGES=$@
 fi
 
-exit $?
+for PACKAGE in $PACKAGES; do
+
+    PACKAGE_DIR=$DIR/packages/$PACKAGE
+
+    if [ -d $PACKAGE_DIR ]; then
+        echo " ***** PACKAGE $PACKAGE" | purple
+
+        echo " ***** INSTALLING..." | purple
+        bash $PACKAGE_DIR/install
+
+        echo " ***** TESTING..." | purple
+        if [ -f $PACKAGE_DIR/test.R ]; then
+            sudo R -f $PACKAGE_DIR/test.R
+        else
+            sudo R -e "install.packages('$PACKAGE', repos='http://cran.rstudio.com/'); library('$PACKAGE')"
+        fi
+
+        return_code=$?
+        if [[ $return_code != 0 ]] ; then
+            echo "$PACKAGE... FAILED" | red
+            exit $return_code
+        else
+            echo "$PACKAGE... SUCCESS" | green
+        fi
+    else
+        echo "Unable to find '$PACKAGE' in $DIR/packages, exiting..." | red
+        exit 1
+    fi
+done
+
+exit 0
